variable "vpc_cidr" {}
variable "max_subnets" {}
variable "public_subnet_count" {}
variable "private_subnet_count" {}
variable "public_cidrs" {}
variable "private_cidrs" {}
variable "security_group" {}
variable "db_subnet_group" {}
variable "db_subnet_group_name" {}
variable "db_subnet_group_tags" {}
